// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import StatusBannerController from "./status_banner_controller"
application.register("status-banner", StatusBannerController)

import CharCounterController from "./char_counter_controller"
application.register("char-counter", CharCounterController)

import GenerationFormController from "./generation_form_controller"
application.register("generation-form", GenerationFormController)

import ProposalsListController from "./proposals_list_controller"
application.register("proposals-list", ProposalsListController)

import ProposalCardController from "./proposal_card_controller"
application.register("proposal-card", ProposalCardController)
